In [28]:
import pandas as pd
import re

In [17]:
df = pd.read_csv("/home/moraa-ontita/Documents/Machine-learning/talent_survey/data/Louisville_Metro_KY_-_Open_Data_Data_Set_Inventory_Updated_for_2019.csv")

In [18]:
df.head()

,ObjectId,Data_Set_Name,Brief_Description_of_Data,Data_Source,Home_Department,Home_Department_Division,Data_Steward__Business__Name,Data_Custodian__Technical__Name,Data_Classification,Data_Format,Frequency_of_Data_Change,Time_Span,Start_Date,End_Date,Geographic_Coverage,Geographic_Granularity,Link_to_Existing_Publication
0,1,Meter,"Meter Information, location type, rates etc\n\n",Meter Bagging,Parking Authority of River City,NaN,NaN,NaN,Public,Access Consolidated Database,Continuous,NaN,NaN,NaN,Citywide,Not applicable,NaN
1,2,Property Maintenance Cases,NaN,Hansen 8,Codes & Regulations,Property Maintenance Division,Benjamin Anderson,NaN,Public,csv file,Not updated (historical only),5 Years,NaN,NaN,Citywide,Latitude/longitude;#Street address,https://data.louisvilleky.gov/dataset/property...
2,3,Order Meter,Data on orders with meter information\n\n,Meter Bagging,Parking Authority of River City,NaN,NaN,NaN,Public,Access Consolidated Database,Continuous,2007-,NaN,NaN,Citywide,Not applicable,NaN
3,4,Meter Order Summary,​Order centric data for Meter Bagging\n,NaN,Parking Authority of River City,On Street,NaN,NaN,Public,Unknown,Continuous,2007-,NaN,NaN,Citywide,Not applicable,NaN
4,5,Passport Transaction Detail,NaN,Passport (GO502),Parking Authority of River City,NaN,NaN,NaN,Internal,Excel Spread Sheets,Continuous,NaN,NaN,NaN,Citywide,Not applicable,NaN

# Handling missing values

In [19]:
# Dropping columns with too many missing values
df.drop(columns=['End_Date', 'Start_Date'], inplace=True)

In [20]:
df.head()

,ObjectId,Data_Set_Name,Brief_Description_of_Data,Data_Source,Home_Department,Home_Department_Division,Data_Steward__Business__Name,Data_Custodian__Technical__Name,Data_Classification,Data_Format,Frequency_of_Data_Change,Time_Span,Geographic_Coverage,Geographic_Granularity,Link_to_Existing_Publication
0,1,Meter,"Meter Information, location type, rates etc\n\n",Meter Bagging,Parking Authority of River City,NaN,NaN,NaN,Public,Access Consolidated Database,Continuous,NaN,Citywide,Not applicable,NaN
1,2,Property Maintenance Cases,NaN,Hansen 8,Codes & Regulations,Property Maintenance Division,Benjamin Anderson,NaN,Public,csv file,Not updated (historical only),5 Years,Citywide,Latitude/longitude;#Street address,https://data.louisvilleky.gov/dataset/property...
2,3,Order Meter,Data on orders with meter information\n\n,Meter Bagging,Parking Authority of River City,NaN,NaN,NaN,Public,Access Consolidated Database,Continuous,2007-,Citywide,Not applicable,NaN
3,4,Meter Order Summary,​Order centric data for Meter Bagging\n,NaN,Parking Authority of River City,On Street,NaN,NaN,Public,Unknown,Continuous,2007-,Citywide,Not applicable,NaN
4,5,Passport Transaction Detail,NaN,Passport (GO502),Parking Authority of River City,NaN,NaN,NaN,Internal,Excel Spread Sheets,Continuous,NaN,Citywide,Not applicable,NaN

In [21]:
# Fill missing values in other columns
df['Brief_Description_of_Data'] = df['Brief_Description_of_Data'].fillna('No description provided')
df['Data_Source'] = df['Data_Source'].fillna('Unknown')
df['Time_Span'].fillna('Unknown', inplace=True)
df['Home_Department_Division'] = df['Home_Department_Division'].fillna('Unspecified')
df['Data_Steward__Business__Name'] = df['Data_Steward__Business__Name'].fillna('Not listed')
df['Data_Custodian__Technical__Name'] = df['Data_Custodian__Technical__Name'].fillna('Not listed')
df['Link_to_Existing_Publication'] = df['Link_to_Existing_Publication'].fillna('No link available')

/tmp/ipykernel_947055/137015243.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Time_Span'].fillna('Unknown', inplace=True)

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 143 entries, 0 to 142
Data columns (total 15 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   ObjectId                         143 non-null    int64
 1   Data_Set_Name                    143 non-null    object
 2   Brief_Description_of_Data        143 non-null    object
 3   Data_Source                      143 non-null    object
 4   Home_Department                  143 non-null    object
 5   Home_Department_Division         143 non-null    object
 6   Data_Steward__Business__Name     143 non-null    object
 7   Data_Custodian__Technical__Name  143 non-null    object
 8   Data_Classification              143 non-null    object
 9   Data_Format                      143 non-null    object
 10  Frequency_of_Data_Change         143 non-null    object
 11  Time_Span                        143 non-null    object
 12  Geographic_Coverage              143 non-null    object
 13  Geographic_Granularity           143 non-null    object
 14  Link_to_Existing_Publication     143 non-null    object
dtypes: int64(1), object(14)
memory usage: 16.9+ KB

# Cleaning Text and Columns

In [23]:
text_columns = [
    'Brief_Description_of_Data',
    'Data_Source',
    'Home_Department',
    'Home_Department_Division',
    'Data_Steward__Business__Name',
    'Data_Custodian__Technical__Name',
    'Data_Format',
    'Frequency_of_Data_Change',
    'Time_Span',
    'Geographic_Coverage',
    'Geographic_Granularity',
    'Link_to_Existing_Publication'
]

# Strip whitespace and remove newline characters
for col in text_columns:
    df[col] = df[col].astype(str).str.strip().str.replace(r'[\n\r]+', ' ', regex=True)

In [24]:
df.head()

,ObjectId,Data_Set_Name,Brief_Description_of_Data,Data_Source,Home_Department,Home_Department_Division,Data_Steward__Business__Name,Data_Custodian__Technical__Name,Data_Classification,Data_Format,Frequency_of_Data_Change,Time_Span,Geographic_Coverage,Geographic_Granularity,Link_to_Existing_Publication
0,1,Meter,"Meter Information, location type, rates etc",Meter Bagging,Parking Authority of River City,Unspecified,Not listed,Not listed,Public,Access Consolidated Database,Continuous,Unknown,Citywide,Not applicable,No link available
1,2,Property Maintenance Cases,No description provided,Hansen 8,Codes & Regulations,Property Maintenance Division,Benjamin Anderson,Not listed,Public,csv file,Not updated (historical only),5 Years,Citywide,Latitude/longitude;#Street address,https://data.louisvilleky.gov/dataset/property...
2,3,Order Meter,Data on orders with meter information,Meter Bagging,Parking Authority of River City,Unspecified,Not listed,Not listed,Public,Access Consolidated Database,Continuous,2007-,Citywide,Not applicable,No link available
3,4,Meter Order Summary,​Order centric data for Meter Bagging,Unknown,Parking Authority of River City,On Street,Not listed,Not listed,Public,Unknown,Continuous,2007-,Citywide,Not applicable,No link available
4,5,Passport Transaction Detail,No description provided,Passport (GO502),Parking Authority of River City,Unspecified,Not listed,Not listed,Internal,Excel Spread Sheets,Continuous,Unknown,Citywide,Not applicable,No link available

In [25]:
df.columns

Index(['ObjectId', 'Data_Set_Name', 'Brief_Description_of_Data', 'Data_Source',
       'Home_Department', 'Home_Department_Division',
       'Data_Steward__Business__Name', 'Data_Custodian__Technical__Name',
       'Data_Classification', 'Data_Format', 'Frequency_of_Data_Change',
       'Time_Span', 'Geographic_Coverage', 'Geographic_Granularity',
       'Link_to_Existing_Publication'],
      dtype='object')

In [26]:
# Standardize capitalization
df['Home_Department'] = df['Home_Department'].str.title()
df['Home_Department_Division'] = df['Home_Department_Division'].str.title()
df['Data_Source'] = df['Data_Source'].str.title()
df['Data_Format'] = df['Data_Format'].str.title()

In [27]:
df.head()

,ObjectId,Data_Set_Name,Brief_Description_of_Data,Data_Source,Home_Department,Home_Department_Division,Data_Steward__Business__Name,Data_Custodian__Technical__Name,Data_Classification,Data_Format,Frequency_of_Data_Change,Time_Span,Geographic_Coverage,Geographic_Granularity,Link_to_Existing_Publication
0,1,Meter,"Meter Information, location type, rates etc",Meter Bagging,Parking Authority Of River City,Unspecified,Not listed,Not listed,Public,Access Consolidated Database,Continuous,Unknown,Citywide,Not applicable,No link available
1,2,Property Maintenance Cases,No description provided,Hansen 8,Codes & Regulations,Property Maintenance Division,Benjamin Anderson,Not listed,Public,Csv File,Not updated (historical only),5 Years,Citywide,Latitude/longitude;#Street address,https://data.louisvilleky.gov/dataset/property...
2,3,Order Meter,Data on orders with meter information,Meter Bagging,Parking Authority Of River City,Unspecified,Not listed,Not listed,Public,Access Consolidated Database,Continuous,2007-,Citywide,Not applicable,No link available
3,4,Meter Order Summary,​Order centric data for Meter Bagging,Unknown,Parking Authority Of River City,On Street,Not listed,Not listed,Public,Unknown,Continuous,2007-,Citywide,Not applicable,No link available
4,5,Passport Transaction Detail,No description provided,Passport (Go502),Parking Authority Of River City,Unspecified,Not listed,Not listed,Internal,Excel Spread Sheets,Continuous,Unknown,Citywide,Not applicable,No link available

In [29]:
# Fix Formatting in Time_Span
def clean_time_span(span):
    if pd.isna(span) or span.lower() in ['nan', 'none']:
        return 'Not specified'
    span = span.strip()
    if re.fullmatch(r'\d{4}-', span):  # e.g., "2007-"
        return span.replace('-', ' to present')
    if re.fullmatch(r'\d{4}-\d{4}', span):  # e.g., "2010-2015"
        return span.replace('-', ' to ')
    return span  # return original if no change needed

df['Time_Span'] = df['Time_Span'].apply(clean_time_span)

In [30]:
df['Time_Span'].head()

0            Unknown
1            5 Years
2    2007 to present
3    2007 to present
4            Unknown
Name: Time_Span, dtype: object

In [34]:
import os

# Get current working directory (should be inside src/section1/notebooks)
notebook_dir = os.getcwd()

# Go up three levels to reach 'talent_survey'
project_root = os.path.abspath(os.path.join(notebook_dir, "../../../"))

# Define and create artifacts/cleaned directory
output_dir = os.path.join(project_root, "artifacts", "cleaned")
os.makedirs(output_dir, exist_ok=True)

# Define path to the cleaned CSV
output_path = os.path.join(output_dir, "cleaned_dataset.csv")

# Save the DataFrame
df.to_csv(output_path, index=False)

print(f"CSV saved to: {output_path}")

CSV saved to: /home/moraa-ontita/Documents/Machine-learning/talent_survey/artifacts/cleaned/cleaned_dataset.csv